import type { Event } from "@/lib/types"

export const events: Event[] = [
  {
    id: "1",
    title: "Festival de Rock Nacional",
    description: "Os maiores sucessos do rock brasileiro em uma noite inesquecível",
    fullDescription:
      "Prepare-se para uma noite épica com os maiores nomes do rock nacional! Este festival reunirá bandas icônicas e emergentes em um espetáculo que celebra a rica tradição do rock brasileiro. Com mais de 8 horas de música, food trucks, área VIP e muito mais. Uma experiência única para os amantes do rock!",
    date: "2024-03-15",
    time: "20:00",
    location: "São Paulo, SP",
    venue: "Estádio do Morumbi",
    price: 120,
    originalPrice: 150,
    category: "Música",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4.8,
    reviews: 1250,
    capacity: 50000,
    sold: 35000,
    featured: true,
    organizer: "Rock Brasil Eventos",
    ageRating: "16 anos",
    sectors: [
      {
        id: "pista",
        name: "Pista",
        description: "Área próxima ao palco, em pé",
        price: 120,
        originalPrice: 150,
        available: 8000,
        total: 10000,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 120, originalPrice: 150 },
          { id: "meia", name: "Meia Entrada", price: 60, description: "Necessário comprovação" },
          {
            id: "solidario",
            name: "Ingresso Solidário",
            price: 90,
            description: "Doação de 1kg de alimento não perecível",
          },
        ],
      },
      {
        id: "arquibancada",
        name: "Arquibancada",
        description: "Assentos numerados com boa visão",
        price: 180,
        originalPrice: 220,
        available: 5000,
        total: 8000,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 180, originalPrice: 220 },
          { id: "meia", name: "Meia Entrada", price: 90, description: "Necessário comprovação" },
        ],
      },
      {
        id: "camarote",
        name: "Camarote",
        description: "Área VIP com bar exclusivo e buffet",
        price: 350,
        originalPrice: 400,
        available: 200,
        total: 500,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 350, originalPrice: 400 }],
      },
      {
        id: "cadeira-especial",
        name: "Cadeira Especial",
        description: "Assentos premium com vista privilegiada",
        price: 280,
        available: 800,
        total: 1000,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 280 },
          { id: "meia", name: "Meia Entrada", price: 140, description: "Necessário comprovação" },
        ],
      },
    ],
    videos: [
      {
        id: "1",
        title: "Evidências",
        artist: "Chitãozinho & Xororó",
        videoId: "ePjtnSPFWK8",
      },
      {
        id: "2",
        title: "Tempo Perdido",
        artist: "Legião Urbana",
        videoId: "wjCBt77_E8E",
      },
      {
        id: "3",
        title: "Pais e Filhos",
        artist: "Legião Urbana",
        videoId: "YQQ2StSwg_s",
      },
      {
        id: "4",
        title: "Faroeste Caboclo",
        artist: "Legião Urbana",
        videoId: "jqFICOm8_Hs",
      },
    ],
    salesLocations: [
      {
        id: "loc1",
        name: "Bilheteria Oficial - Estádio do Morumbi",
        address: "Praça Roberto Gomes Pedrosa, 1 - Morumbi",
        city: "São Paulo",
        state: "SP",
        zipCode: "05653-070",
        hours: "Seg-Sex: 10h-18h",
        phone: "(11) 3749-0000",
        mapLink: "https://maps.app.goo.gl/example1",
      },
      {
        id: "loc2",
        name: "Loja TicketHub - Shopping Paulista",
        address: "Rua Treze de Maio, 1947 - Bela Vista",
        city: "São Paulo",
        state: "SP",
        zipCode: "01327-000",
        hours: "Seg-Sab: 10h-22h, Dom: 14h-20h",
        phone: "(11) 3179-0000",
        mapLink: "https://maps.app.goo.gl/example2",
      },
    ],
  },
  {
    id: "2",
    title: "Stand-up Comedy Night",
    description: "Uma noite de muito humor com os melhores comediantes do país",
    fullDescription:
      "Venha se divertir com uma seleção dos melhores comediantes do Brasil! Uma noite repleta de risadas garantidas com apresentações exclusivas e muito humor inteligente. O evento conta com bar completo e ambiente climatizado para sua comodidade.",
    date: "2024-03-20",
    time: "21:00",
    location: "Rio de Janeiro, RJ",
    venue: "Teatro Riachuelo",
    price: 80,
    category: "Comédia",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4.6,
    reviews: 890,
    capacity: 1500,
    sold: 1200,
    featured: false,
    organizer: "Humor & Cia",
    ageRating: "18 anos",
    sectors: [
      {
        id: "plateia",
        name: "Plateia",
        description: "Assentos na plateia principal",
        price: 80,
        available: 200,
        total: 800,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 80 },
          { id: "meia", name: "Meia Entrada", price: 40, description: "Necessário comprovação" },
        ],
      },
      {
        id: "balcao",
        name: "Balcão",
        description: "Assentos no balcão superior",
        price: 60,
        available: 100,
        total: 400,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 60 }],
      },
      {
        id: "vip",
        name: "Mesa VIP",
        description: "Mesa para 4 pessoas com serviço de mesa",
        price: 150,
        available: 20,
        total: 75,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 150 }],
      },
    ],
    salesLocations: [
      {
        id: "loc3",
        name: "Bilheteria do Teatro Riachuelo",
        address: "Rua do Passeio, 40 - Centro",
        city: "Rio de Janeiro",
        state: "RJ",
        zipCode: "20021-290",
        hours: "Ter-Dom: 14h-20h",
        phone: "(21) 2533-0000",
        mapLink: "https://maps.app.goo.gl/example3",
      },
    ],
  },
  {
    id: "3",
    title: "Festival Gastronômico",
    description: "Sabores únicos dos melhores chefs do Brasil",
    fullDescription:
      "Uma experiência gastronômica única com os melhores chefs do país! Deguste pratos exclusivos, participe de workshops culinários e conheça as últimas tendências da gastronomia brasileira. O evento inclui degustações, aulas práticas e muito mais.",
    date: "2024-03-25",
    time: "18:00",
    location: "Belo Horizonte, MG",
    venue: "Parque Municipal",
    price: 95,
    category: "Gastronomia",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4.7,
    reviews: 650,
    capacity: 3000,
    sold: 2100,
    featured: true,
    organizer: "Sabores do Brasil",
    ageRating: "Livre",
    sectors: [
      {
        id: "geral",
        name: "Entrada Geral",
        description: "Acesso a todas as áreas do festival",
        price: 95,
        available: 600,
        total: 2000,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 95 }],
      },
      {
        id: "workshop",
        name: "Entrada + Workshop",
        description: "Inclui participação em workshops culinários",
        price: 150,
        available: 200,
        total: 500,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 150 }],
      },
      {
        id: "degustacao-premium",
        name: "Degustação Premium",
        description: "Acesso VIP com degustação exclusiva",
        price: 220,
        available: 100,
        total: 300,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 220 }],
      },
    ],
  },
  {
    id: "4",
    title: "Conferência de Tecnologia",
    description: "As últimas tendências em tecnologia e inovação",
    fullDescription:
      "A maior conferência de tecnologia do país! Palestras com especialistas internacionais, workshops práticos, networking e as últimas novidades em IA, blockchain, desenvolvimento web e muito mais. Imperdível para profissionais da área tech.",
    date: "2024-04-02",
    time: "09:00",
    location: "São Paulo, SP",
    venue: "Centro de Convenções",
    price: 200,
    category: "Tecnologia",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4.9,
    reviews: 420,
    capacity: 2000,
    sold: 1800,
    featured: false,
    organizer: "TechBrasil",
    ageRating: "Livre",
    sectors: [
      {
        id: "individual",
        name: "Ingresso Individual",
        description: "Acesso a todas as palestras e networking",
        price: 200,
        available: 150,
        total: 1500,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 200 },
          { id: "estudante", name: "Estudante", price: 100, description: "Necessário comprovação" },
        ],
      },
      {
        id: "workshop",
        name: "Individual + Workshops",
        description: "Inclui workshops práticos exclusivos",
        price: 350,
        available: 40,
        total: 300,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 350 }],
      },
      {
        id: "corporativo",
        name: "Pacote Corporativo",
        description: "Para empresas - inclui material e certificado",
        price: 450,
        available: 10,
        total: 100,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 450 }],
      },
    ],
  },
  {
    id: "5",
    title: "Show de Samba",
    description: "Uma celebração da cultura brasileira com muito samba",
    fullDescription:
      "Celebre a cultura brasileira em uma noite especial de samba! Com apresentações de escolas de samba, roda de samba ao vivo, comidas típicas e muita alegria. Uma verdadeira festa da cultura nacional que você não pode perder!",
    date: "2024-04-10",
    time: "19:30",
    location: "Rio de Janeiro, RJ",
    venue: "Sambódromo",
    price: 75,
    category: "Música",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4.5,
    reviews: 980,
    capacity: 8000,
    sold: 6500,
    featured: false,
    organizer: "Samba Carioca",
    ageRating: "Livre",
    sectors: [
      {
        id: "arquibancada-popular",
        name: "Arquibancada Popular",
        description: "Assentos na arquibancada geral",
        price: 75,
        available: 1000,
        total: 4000,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 75 },
          { id: "meia", name: "Meia Entrada", price: 37.5, description: "Necessário comprovação" },
        ],
      },
      {
        id: "setor-1",
        name: "Setor 1",
        description: "Assentos numerados próximos à pista",
        price: 120,
        available: 400,
        total: 2000,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 120 },
          { id: "meia", name: "Meia Entrada", price: 60, description: "Necessário comprovação" },
        ],
      },
      {
        id: "camarote-samba",
        name: "Camarote Samba",
        description: "Camarote com open bar e comidas típicas",
        price: 250,
        available: 50,
        total: 200,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 250 }],
      },
      {
        id: "frisas",
        name: "Frisas",
        description: "Frisas para até 6 pessoas",
        price: 180,
        available: 100,
        total: 300,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 180 }],
      },
    ],
    videos: [
      {
        id: "1",
        title: "Aquarela do Brasil",
        artist: "Ary Barroso",
        videoId: "5U3jta7D3_g",
      },
      {
        id: "2",
        title: "Mas Que Nada",
        artist: "Jorge Ben Jor",
        videoId: "at02Fvdhk2I",
      },
      {
        id: "3",
        title: "Garota de Ipanema",
        artist: "Tom Jobim & Vinícius de Moraes",
        videoId: "UJkxFhFRFDA",
      },
      {
        id: "4",
        title: "Samba de Uma Nota Só",
        artist: "Tom Jobim",
        videoId: "32C2eLKFBb0",
      },
    ],
  },
  {
    id: "6",
    title: "Peça Teatral Clássica",
    description: "Uma adaptação moderna de um clássico da literatura",
    fullDescription:
      "Uma adaptação contemporânea de um grande clássico da literatura mundial. Com direção premiada e elenco renomado, esta peça promete emocionar e surpreender o público com uma nova perspectiva sobre uma história atemporal.",
    date: "2024-04-15",
    time: "20:30",
    location: "Brasília, DF",
    venue: "Teatro Nacional",
    price: 60,
    category: "Teatro",
    image: "/placeholder.svg?height=400&width=600",
    rating: 4.4,
    reviews: 320,
    capacity: 1200,
    sold: 800,
    featured: false,
    organizer: "Companhia Teatral Nacional",
    ageRating: "12 anos",
    sectors: [
      {
        id: "plateia",
        name: "Plateia",
        description: "Assentos na plateia principal",
        price: 60,
        available: 250,
        total: 600,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 60 },
          { id: "meia", name: "Meia Entrada", price: 30, description: "Necessário comprovação" },
        ],
      },
      {
        id: "balcao-nobre",
        name: "Balcão Nobre",
        description: "Assentos no balcão com vista privilegiada",
        price: 90,
        available: 100,
        total: 300,
        ticketTypes: [
          { id: "inteira", name: "Inteira", price: 90 },
          { id: "meia", name: "Meia Entrada", price: 45, description: "Necessário comprovação" },
        ],
      },
      {
        id: "camarotes",
        name: "Camarotes",
        description: "Camarotes privativos para até 8 pessoas",
        price: 150,
        available: 20,
        total: 50,
        ticketTypes: [{ id: "inteira", name: "Inteira", price: 150 }],
      },
    ],
  },
]
