// Barrel de autenticação
export * from './hooks/useRegister'
export * from './hooks/useLogin'
export * from './hooks/useAutoLogin'
export * from './hooks/useRegisterWithAutoLogin'
export * from './hooks/useSession'
export * from './authService'
export * from './types'
export * from './validation' 